<?php
//Define interface class for router
use \Psr\Http\Message\ServerRequestInterface as Request;        //PSR7 ServerRequestInterface   >> Each router file must contains this
use \Psr\Http\Message\ResponseInterface as Response;            //PSR7 ResponseInterface        >> Each router file must contains this

//Define your modules class
use \modules\first_mod\FirstMod as FirstMod;                    //Your main modules class

//Define additional class for any purpose
use \classes\middleware\ApiKey as ApiKey;                       //ApiKey Middleware             >> To authorize request by using ApiKey generated by reSlim


    // Get module information
    $app->get('/first_mod/get/info/', function (Request $request, Response $response) {
        $fm = new FirstMod($this->db);
        $body = $response->getBody();
        $response = $this->cache->withEtag($response, $this->etag2hour.'-'.trim($_SERVER['REQUEST_URI'],'/'));
        $body->write($fm->viewInfo());
        return classes\Cors::modify($response,$body,200);
    })->add(new ApiKey);

    
    // Token Validation 
    $app->get('/first_mod/check/token/{username}/{token}', function (Request $request, Response $response) {
        $fm = new FirstMod($this->db);
        $fm->username = $request->getAttribute('username');
        $fm->token = $request->getAttribute('token');
        $body = $response->getBody();
        $body->write($fm->checkToken());
        return classes\Cors::modify($response,$body,200);
    });