<?php
//Define interface class for router
use \Psr\Http\Message\ServerRequestInterface as Request;        //PSR7 ServerRequestInterface   >> Each router file must contains this
use \Psr\Http\Message\ResponseInterface as Response;            //PSR7 ResponseInterface        >> Each router file must contains this

//Define your modules class
use \modules\crud_mod\CrudMod as CrudMod;                       //Your main modules class

//Define additional class for any purpose
use \classes\middleware\ValidateParam as ValidateParam;         //ValidateParam                 >> To validate the body form request  
use \classes\middleware\ValidateParamURL as ValidateParamURL;   //ValidateParamURL              >> To validate the query parameter url
use \classes\middleware\ApiKey as ApiKey;                       //ApiKey Middleware             >> To authorize request by using ApiKey generated by reSlim
use \classes\SimpleCache as SimpleCache;                        //SimpleCache class             >> To cache response ouput server side
use \classes\JSON as JSON;                                      //JSON class                    >> To handle JSON in better way (also for debug purpose)

    // Get module information (include cache)
    $app->get('/modules/crud_mod/get/info/', function (Request $request, Response $response) {
        $cm = new CrudMod($this->db);
        $body = $response->getBody();
        $response = $this->cache->withEtag($response, $this->etag2hour.'-'.trim($_SERVER['REQUEST_URI'],'/'));
        if (SimpleCache::isCached(3600,["apikey"])){
            $datajson = SimpleCache::load(["apikey"]);
        } else {
            $datajson = SimpleCache::save($cm->viewInfo(),["apikey"]);
        }
        $body->write($datajson);
        return classes\Cors::modify($response,$body,200);
    })->add(new ApiKey);

    // Installation 
    $app->get('/modules/crud_mod/install/{username}/{token}', function (Request $request, Response $response) {
        $cm = new CrudMod($this->db);
        $cm->username = $request->getAttribute('username');
        $cm->token = $request->getAttribute('token');
        $body = $response->getBody();
        $body->write($cm->install());
        return classes\Cors::modify($response,$body,200);
    });

    // Uninstall (This will clear all data) 
    $app->get('/modules/crud_mod/uninstall/{username}/{token}', function (Request $request, Response $response) {
        $cm = new CrudMod($this->db);
        $cm->username = $request->getAttribute('username');
        $cm->token = $request->getAttribute('token');
        $body = $response->getBody();
        $body->write($cm->uninstall());
        return classes\Cors::modify($response,$body,200);
    });


    //CRUD======================================================


    // POST api to create new data
    $app->post('/modules/crud_mod/create', function (Request $request, Response $response) {
        $cm = new CrudMod($this->db);
        $datapost = $request->getParsedBody();
        $cm->username = $datapost['Username'];
        $cm->token = $datapost['Token'];
        $cm->fullname = $datapost['Fullname'];
        $cm->address = $datapost['Address'];
        $cm->telp = $datapost['Telp'];
        $cm->email = $datapost['Email'];
        $cm->website = $datapost['Website'];
        $body = $response->getBody();
        $body->write($cm->create());
        return classes\Cors::modify($response,$body,200);
    })->add(new ValidateParam('Website','0-50','url'))
        ->add(new ValidateParam('Email','0-50','email'))
        ->add(new ValidateParam('Telp','0-15','numeric'))
        ->add(new ValidateParam('Address','0-250'))
        ->add(new ValidateParam('Token','1-250','required'))
        ->add(new ValidateParam(['Username','Fullname'],'1-50','required'));


    // POST api to update data
    $app->post('/modules/crud_mod/update', function (Request $request, Response $response) {
        $cm = new CrudMod($this->db);
        $datapost = $request->getParsedBody();    
        $cm->username = $datapost['Username'];
        $cm->token = $datapost['Token'];
        $cm->fullname = $datapost['Fullname'];
        $cm->address = $datapost['Address'];
        $cm->telp = $datapost['Telp'];
        $cm->email = $datapost['Email'];
        $cm->website = $datapost['Website'];
        $cm->id = $datapost['ID'];
        $body = $response->getBody();
        $body->write($cm->update());
        return classes\Cors::modify($response,$body,200);
    })->add(new ValidateParam('Website','0-50','url'))
        ->add(new ValidateParam('Email','0-50','email'))
        ->add(new ValidateParam('Telp','0-15','numeric'))
        ->add(new ValidateParam('Address','0-250'))
        ->add(new ValidateParam('ID','1-11','numeric'))
        ->add(new ValidateParam('Token','1-250','required'))
        ->add(new ValidateParam(['Username','Fullname'],'1-50','required'));


    // POST api to delete data
    $app->post('/modules/crud_mod/delete', function (Request $request, Response $response) {
        $cm = new CrudMod($this->db);
        $datapost = $request->getParsedBody();    
        $cm->id = $datapost['ID'];
        $cm->username = $datapost['Username'];
        $cm->token = $datapost['Token'];
        $body = $response->getBody();
        $body->write($cm->delete());
        return classes\Cors::modify($response,$body,200);
    })->add(new ValidateParam('ID','1-11','numeric'))
        ->add(new ValidateParam('Token','1-250','required'))
        ->add(new ValidateParam('Username','1-50','required'));


    // GET api to show all data (index) with pagination server side
    $app->get('/modules/crud_mod/index/{username}/{token}/{page}/{itemsperpage}/', function (Request $request, Response $response) {
        $cm = new CrudMod($this->db);
        $cm->search = filter_var((empty($_GET['query'])?'':$_GET['query']),FILTER_SANITIZE_STRING);
        $cm->username = $request->getAttribute('username');
        $cm->token = $request->getAttribute('token');
        $cm->page = $request->getAttribute('page');
        $cm->itemsPerPage = $request->getAttribute('itemsperpage');
        $body = $response->getBody();
        $body->write($cm->index());
        return classes\Cors::modify($response,$body,200);
    })->add(new ValidateParamURL('query'));


    // GET api to read single data
    $app->get('/modules/crud_mod/read/{id}/{username}/{token}', function (Request $request, Response $response) {
        $cm = new CrudMod($this->db);
        $cm->username = $request->getAttribute('username');
        $cm->token = $request->getAttribute('token');
        $cm->id = $request->getAttribute('id');
        $body = $response->getBody();
        $body->write($cm->read());
        return classes\Cors::modify($response,$body,200);
    });